name: stride
description: Application de génération d'itinéraires de balades personnalisées.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  maplibre_gl: ^0.26.0 # Version hypothétique ou récente pour intégration OSM
  geolocator: ^14.0.2 # Pour récupérer la position GPS
  url_launcher: ^6.2.0 # Pour ouvrir Google Maps / Apple Maps
  share_plus: ^12.0.2
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/map_style.json
